name: eazigrid
description: Easy dynamic flutter row to list/grid widget. This widget arranges children as a row and or grid depending on the constraints of it's parent.
homepage: https://github.com/Algure/eazigrid
version: 0.0.1


environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:


